repos:
    -   repo: https://github.com/pre-commit/pre-commit-hooks
        rev: v4.3.0
        hooks:
        -   id: end-of-file-fixer
            exclude: ^nf_tower_sdk/nft/
        -   id: trailing-whitespace
            exclude: ^nf_tower_sdk/nft/
    -   repo: https://github.com/psf/black
        rev: 22.6.0
        hooks:
        -   id: black
            exclude: ^nf_tower_sdk/nft/
    -   repo: local
        hooks:
        -   id: pylint
            name: pylint
            entry: pylint
            language: system
            types: [python]
            require_serial: true
            exclude: ^nf_tower_sdk/nft/
