"""Client for Nextflow Tower API."""

from nf_tower_sdk.clients import (
    ComputeEnvs,
    Orgs,
    Pipelines,
    Workflows,
    Workspaces,
)
from nf_tower_sdk.interfaces import NextflowTowerClientInterface
from nf_tower_sdk.nft.api_library import AuthenticatedClient


# pylint: disable=too-few-public-methods
class NextflowTowerClient(NextflowTowerClientInterface):
    """
    Client for consuming Nextflow Tower API.

    The client is using an autogenerated API client SDK.
    The SDK library was generated
    using https://github.com/openapi-generators/openapi-python-client
    and the NFT OpenAPI schema
    at https://tower.nf/openapi/nextflow-tower-api-latest.yml
    """

    _url: str

    def __init__(
        self,
        url: str,
        api_token: str,
        timeout: int = 20.0,
    ):
        """
        Client which has been authenticated for Nextflow Tower API.

        :param url: URL for Nextflow tower. Example "https://tower.nf".
        :param api_token: Tower API authentication token.
        :param timeout: The maximum amount of a time in seconds a request can take.
             API functions will raise httpx.TimeoutException if this is exceeded.
        """
        self._url = url
        client = AuthenticatedClient(
            base_url=f"{url}/api", token=api_token, timeout=timeout
        )
        self.compute_envs = ComputeEnvs(client)
        self.orgs = Orgs(client)
        self.pipelines = Pipelines(client)
        self.workflows = Workflows(client)
        self.workspaces = Workspaces(client)
